### ISSUE TITLE
[Feature] add placemouse patch

### ISSUE THREAD

**Issue by siduck76** [siduck76/chadwm#11]
https://github.com/bakkeby/patches/wiki/placemouse

**Comment by siduck76** [comment]
@Avimitin could you add this patch? I tried patching it but got tons of errors ;(

**Comment by Avimitin** [comment]
You can try to copy and paste the code manually. I fixed some patch conflict in this way.

**Comment by siduck76** [comment]
> You can try to copy and paste the code manually. I fixed some patch conflict in this way.

I did it that way , but still no luck

**Comment by Avimitin** [comment]
> > You can try to copy and paste the code manually. I fixed some patch conflict in this way.
> 
> 
> 
> I did it that way , but still no luck

Maybe you need to focus on the keyboard and forget the mouse? :) 

I'll try to patch it once I have leisure. I'm sorry that I can't even read the source code because it's full of "x" and "bh" and "sel" and lot's of variable which is so suck that I can't figure out what it means. So I can't guarantee that I can fix this.

**Comment by siduck76** [comment]
> > > You can try to copy and paste the code manually. I fixed some patch conflict in this way.
> > 
> > 
> > I did it that way , but still no luck
> 
> Maybe you need to focus on the keyboard and forget the mouse? :)
> 
> I'll try to patch it once I have leisure. I'm sorry that I can't even read the source code because it's full of "x" and "bh" and "sel" and lot's of variable which is so suck that I can't figure out what it means. So I can't guarantee that I can fix this.

oh lel , nvm then . I'll look on those some day . Have a nice day :'

**Comment by Avimitin** [comment]
Done.


https://user-images.githubusercontent.com/30021675/128352492-a8339853-300e-4367-8573-bce047cb4a7b.mp4

**Comment by siduck76** [comment]
@Avimitin how do we swap the windows? I tried mod + left click drag ( like bspwm has ) , doesnt work.

**Comment by Avimitin** [comment]
> @Avimitin how do we swap the windows? I tried mod + left click drag ( like bspwm has ) , doesnt work.

Have you deleted the config.h file? It works with Mod + Left by default.

**Comment by siduck76** [comment]
> > @Avimitin how do we swap the windows? I tried mod + left click drag ( like bspwm has ) , doesnt work.
> 
> Have you deleted the config.h file and rebuilt? It works with Mod + Left by default.

oh that was it , thanks works now!

**Comment by Avimitin** [comment]
> > > @Avimitin how do we swap the windows? I tried mod + left click drag ( like bspwm has ) , doesnt work.
> > 
> > 
> > Have you deleted the config.h file and rebuilt? It works with Mod + Left by default.
> 
> oh that was it , thanks works now!

Removed config.h in Makefile is necessary when starting to patch dwm. :)
