### ISSUE TITLE
Request diff for tab patch (monocle layout)

### ISSUE THREAD

**Issue by voidstarsh** [siduck76/chadwm#17]
Hi @siduck76, I find your tab patch very interesting. It looks awesome.

Can you share a complete diff for the tab patch? I've got my own build of dwm ([voidstarsh/voidwm](https://github.com/voidstarsh/voidwm)) and I would like to use it in my build. I tried stealin- I mean copying the code from the commit history but it is divided into multiple commits and so far I've added only this https://github.com/siduck76/chadwm/commit/aa15a634d6a5880dbf2a81b692ef93b020a9c16a commit and it looks something like this (https://github.com/voidstarsh/voidwm/commit/e96d6c698bd31ef9d207da6828df400d21e6a00b):

![tab-patch](https://user-images.githubusercontent.com/85620326/128722780-3ebf8e51-646c-4910-b90d-a9d21cb51c53.png)

**Comment by siduck76** [comment]
@voidstarsh my friend has made all of these cool patches like for tag preview,  tab patch and specifically for my build so Idk if those might work on your build unless you manually modify them.

**Comment by voidstarsh** [comment]
I already manually add patches in my build (not using patch -p1 commands, etc). It helps understanding the inner workings of dwm. This patch too was manually added. It would be great if you could provide me with one diff for your entire tab patch.

**Comment by siduck76** [comment]
> I already manually add patches in my build (not using patch -p1 commands, etc). It helps understanding the inner workings of dwm. This patch too was manually added. It would be great if you could provide me with one diff for your entire tab patch.

Idk if I can provide an entire one diff! sorry! My friend sent me a series of patches and gotta find em so I will send those tomorrow .

**Comment by voidstarsh** [comment]
> Idk if I can provide an entire one diff! sorry! My friend sent me a series of patches and gotta find em so I will send those tomorrow .

No problem. I'll do with 'em multiple patches. Thanks! And I know that you know but your build is just beautiful.

**Comment by voidstarsh** [comment]
> Idk if I can provide an entire one diff! sorry! My friend sent me a series of patches and gotta find em so I will send those tomorrow .

Hey @siduck76, did you find those patches?

**Comment by siduck76** [comment]
Sorry for late reply @voidstarsh , check these diffs after 25th July

https://github.com/siduck76/chadwm/commits/main?after=68dc836d0e0a9e0dc84d4bfa8f8b4b7c0e209e7e+34&branch=main

**Comment by voidstarsh** [comment]
Got it. Thanks!

**Comment by Avimitin** [comment]
Here is the patch: https://github.com/Avimitin/sdwm/blob/master/patches/dwm-tab.diff

This patch is base on (`alpha|systray|barpadding|fullgaps`) so you may get errors if you don't have this patch.

If you have any problems, please open the issue at my repository. Do not disturb the author.

**Comment by voidstarsh** [comment]
> This is the patch extracted from siduck76's commit: https://github.com/Avimitin/sdwm/blob/master/patches/dwm-tab.diff
> 
> This patch is base on (`alpha|systray|barpadding|fullgaps`) so you may get errors if you don't have those patches.
> 
> For anyone who have problems, please open the issue at my repository. Do not disturb the author.

Thank you.

**Comment by Avimitin** [comment]
Emmm I will take a look on it. But I haven't written C for a long time and I am looking for a job this days. So I can't finish it ASAP.

**Comment by siduck** [comment]
> Emmm I will take a look at it. But I haven't written C for a long time and I am looking for a job this days. So I can't finish it ASAP.

no worries, take your own time!

**Comment by Avimitin** [comment]
I am sorry that maybe I will not take time to do this. Currently I switched to the KDE plasma and using the wayland protocol. The browsing experience is better than X11. And it is easy to modify the plasma KWin to have dwm like key mappings. So I've gave up using dwm. And I am not gonna use X11 anymore. Sorry for the late respond.
