### ISSUE TITLE
[Question] Which patch implement the feature in the below screenshot?

### ISSUE THREAD

**Issue by Avimitin** [siduck76/chadwm#19]
![image](https://user-images.githubusercontent.com/30021675/129004883-fb903a63-8660-4bf7-b39a-3bf86f72eb61.png)

This feature seems like a tabbed windows manager. It's great for coding and compiling.

**Comment by siduck76** [comment]
Check the recent closed issue!

**Comment by Avimitin** [comment]
I gave up, it’s full of invalid parameters error. Thanks for your reply.

**Comment by Avimitin** [comment]
For people who have errors: `X_Error BadMatch Invalid parameters`, you can try to replace the tab win create parameters to:

```c
m->tabwin = XCreateWindow(dpy, root, m->wx, m->ty, m->ww, th, 0, depth,
					        InputOutput, visual,
						CWOverrideRedirect|CWBackPixel|CWBorderPixel|CWColormap|CWEventMask, &wa);
```

**Comment by Avimitin** [comment]
> For people who have errors: `X_Error BadMatch Invalid parameters`, you can try to replace the tab win create parameters to:
> 
> ```c
> m->tabwin = XCreateWindow(dpy, root, m->wx, m->ty, m->ww, th, 0, depth,
> 			  InputOutput, visual,
> 			  CWOverrideRedirect|CWBackPixel|CWBorderPixel|CWColormap|CWEventMask, &wa);
> ```

Exactly, this error is came from alpha patch. You must create tab window like the status bar. For more detail please checkout https://dwm.suckless.org/patches/alpha/dwm-alpha-20201019-61bb8b2.diff and search the keyword `XCreateWindow` at function `updatebars(void)`.

**Comment by siduck76** [comment]
> > For people who have errors: `X_Error BadMatch Invalid parameters`, you can try to replace the tab win create parameters to:
> > ```c
> > m->tabwin = XCreateWindow(dpy, root, m->wx, m->ty, m->ww, th, 0, depth,
> > 			  InputOutput, visual,
> > 			  CWOverrideRedirect|CWBackPixel|CWBorderPixel|CWColormap|CWEventMask, &wa);
> > ```
> 
> Exactly, this error is coming from the alpha patch. You must create a tab window like the status bar. For more detail please check out https://dwm.suckless.org/patches/alpha/dwm-alpha-20201019-61bb8b2.diff and search the keyword `XCreateWindow` at function `updatebars(void)`.

yeah chadwm doesnt have the alpha patch so I didnt had those issues

**Comment by Avimitin** [comment]
Tab patch file link: https://github.com/siduck76/chadwm/issues/17#issuecomment-896920317
