### ISSUE TITLE
Removing statusbar gaps only

### ISSUE THREAD

**Issue by Kastakin** [siduck76/chadwm#21]
Hello! 
Just found this dwm build and I was toying with it but I can't seem to figure out how to disable the gaps for the status bar only.

I thought it was related to the patch [barpadding](https://dwm.suckless.org/patches/barpadding/) but I can't seem to find the `vertpad` and `sidepad` variables that are referenced in the patch page. 

I seem to have figured out that `horizpadbar` and `vertpadbar` are related to the [statuspadding](https://dwm.suckless.org/patches/statuspadding/) patch so going by exclusion I thought that `vertpadtab`, `horizpadtabi` and `horizpadtabo` are the ones that should be changed to 0 to achieve the "gapless statusbar" I was looking for. 

Actually assigning 0 to those variables, make clean install and restarting dwm results in a crash.

I'm not an expert whatsoever but if more info is needed I'm more then happy to help!

**Comment by siduck76** [comment]
sorry for the trouble! chadwm has bar padding around it according to the gaps so when you can gaps the bar size padding changes too. just revert this commit https://github.com/siduck76/chadwm/commit/ee720a8c603fa2d7993fdf569e15e9b452e45fa7

**Comment by Kastakin** [comment]
No need to apologize! I'm the one who's the newbie around the topic, thanks for the help!
