### ISSUE TITLE
Super + Tab not switching between the two previous tags

### ISSUE THREAD

**Issue by chown-coffee** [siduck76/chadwm#25]
Hello! First of wall, great job with your projects, they're always incredibly beautiful.

So, I actually already solved the problem I'm gonna report here, but I'm just creating this issue to be sure if that really is or not a problem. When I first installed chadwm, my `Super + Tab` combination was not having the same behavior as vanilla dwm (which is to keep switching between the 2 previous tags). Instead of that, it was going to a *null view*, not related to any tag.
That was also creating some issues with shiftview patch, which I installed after.

Like I said, I already solved, but I was just wondering if this was supposed to be the behavior in chadwm, or is it really an issue?
If it is an issue, I may do a pull request with the solution (if it's necessary, because it's literally an one line change, actually).

Well, that was it. Again, great job with the projects and thanks in advance.

**Comment by siduck76** [comment]
this feature seems useful! send a PR :)
