### ISSUE TITLE
unable to interact with chadwm

### ISSUE THREAD

**Issue by 0xff001** [siduck76/chadwm#27]
i followed the installation steps, and when dwm started, the background was black except for the task bar, i could move my mouse but no keyboard inputs, no shortcuts worked, i couldnt even exit out, i had to boot into the iso to fix it

**Comment by 0xff001** [comment]
by "fix it" i mean not autostart dwm

**Comment by 0xff001** [comment]
how can i make it useable?

**Comment by siduck76** [comment]
> by "fix it" i mean not autostart dwm

because that autostart file is meant for my system , you have to add your stuff . like add your wallpaper etc. remove everything from it except the line having "dwm"

**Comment by 0xff001** [comment]
i did that, same error

**Comment by siduck76** [comment]
> i did that, same error

how are you starting dwm?

**Comment by 0xff001** [comment]
i added exec dwm to .xinitrc, autostart on reboot

**Comment by 0xff001** [comment]
should it be "exec ~/.dwm/autostart" ?

**Comment by 0xff001** [comment]
ok i just tried it, still getting the same error, im using arch-linux if that  helps

**Comment by siduck76** [comment]
> should it be "exec ~/.dwm/autostart" ?

yes , show your autostart

**Comment by siduck76** [comment]
also you need to uncoment one line from config.def.h , read it properly

**Comment by siduck76** [comment]
ok i removed that thing , https://github.com/siduck76/chadwm/blob/main/chadwm/config.def.h#L136 . update config

**Comment by 0xff001** [comment]
I commented that line, still same error

**Comment by 0xff001** [comment]
*uncommented

**Comment by siduck76** [comment]
> I commented that line, still same error

which terminal are u using? st should work ootb with chadwm or u gotta edit config.h

make changes in config.h. stop editing config.def

**Comment by 0xff001** [comment]
I use alacrity should I change my default to st?

**Comment by 0xff001** [comment]
Also, mod shift r does not do anything, is the mod key set to something other than alt in chadwm?

**Comment by siduck76** [comment]
> Also, mod shift r does not do anything, is the mod key set to something other than alt in chadwm?

its super key

**Comment by 0xff001** [comment]
You've got to be kidding me, i used windows key instead of alt, and i got the terminal working, thanks!

**Comment by siduck76** [comment]
Ig this can be closed now :p
