### ISSUE TITLE
I Want The Tabmode Patch

### ISSUE THREAD

**Issue by baizeyv** [siduck76/chadwm#29]
Where Can I Find The Tabmode Patch ?
Please~

**Comment by AlphaTechnolog** [comment]
This?
![tabmode](https://user-images.githubusercontent.com/54639968/133473342-f3cd5436-be58-438e-ab7e-d468bcc0ecbe.png)

**Comment by AlphaTechnolog** [comment]
If yes, open two windows in one workspace, then use `mod+shift+f`. And if you want to switch to tiling layout use `mod+t`. For fullscreen layouts use `mod+f`.

All layouts are created in the `config.def.h` file into the `chadwm` folder.

**Comment by baizeyv** [comment]
> 这个？
> ![标签模式](https://user-images.githubusercontent.com/54639968/133473342-f3cd5436-be58-438e-ab7e-d468bcc0ecbe.png)
Yes, It's This. I Want To Patch To My DWM, But I Havn't This Patch.

**Comment by baizeyv** [comment]
> 如果是，请在一个工作区中打开两个窗口，然后使用`mod+shift+f`. 如果您想切换到平铺布局，请使用`mod+t`. 对于全屏布局，请使用`mod+f`.
> 
> 所有布局都在`config.def.h`文件中创建到文件`chadwm`夹中。

When I Use The chadwm, I Can Toggle To The Tabmode.
Your DWM Is So Beautiful, But I Want Use My DWM, Because My DWM Had Patched Many Patches Yours Doesn't Have .
Thanks To Your Reply.

**Comment by baizeyv** [comment]
I Had Found It!
Is it this?
https://dwm.suckless.org/patches/tab/

**Comment by siduck76** [comment]
> I Had Found It!
> Is it this?
> https://dwm.suckless.org/patches/tab/

no , mine is a modified version of this

**Comment by baizeyv** [comment]
> > I Had Found It!
> > Is it this?
> > https://dwm.suckless.org/patches/tab/
> 
> no , mine is a modified version of this

Do You have The 'diff' File You Had Modified?
I Need It.
Thanks.

**Comment by baizeyv** [comment]
> > > I Had Found It!
> > > Is it this?
> > > https://dwm.suckless.org/patches/tab/
> > 
> > 
> > no , mine is a modified version of this
> 
> Do You have The 'diff' File You Had Modified?
> I Need It.
> Thanks.

If You Have It, Please Tell Me How To Get It.
If You Don't have It, I Will Close This Issue And Create The 'diff' File By Your Source Code.

**Comment by siduck76** [comment]
https://github.com/siduck76/chadwm/issues/17

**Comment by baizeyv** [comment]
Thanks!
Now, I Will Close This Issue.
