### ISSUE TITLE
Question: How did you go inner padding for status2d?

### ISSUE THREAD

**Issue by iRealistiX** [siduck76/chadwm#30]
Basically, I want to apply padding for status2d as shown in the picture below, I thought it was the `statuspadding` patch but it's useless and does not apply what I want it to do
![21-09-21_14h:25](https://user-images.githubusercontent.com/67875888/134170868-47387743-5235-45e3-bf9d-d39e80ac09e2.png)

Here's what I get on my setup:
![21-09-21_14h:32](https://user-images.githubusercontent.com/67875888/134170946-002863af-49b2-4f7a-b494-87cc896e310a.png)

**Comment by iRealistiX** [comment]
Closing this thread since I found your thread on reddit.

**Comment by siduck** [comment]
> Closing this thread since I found your thread on reddit.

were you able to do it for your build?
