### ISSUE TITLE
Bar unintended behaviour when using system tray

### ISSUE THREAD

**Issue by D35P4C1T0** [siduck76/chadwm#31]
I've noticed that once the system tray is populated, the bar does not correctly show the first element from the left. This happens only when the workspace has no windows in it.

![image](https://user-images.githubusercontent.com/42818929/134203100-1df75ed8-43a6-4387-b515-a7dea91f53c7.png)
 This is the top bar with one icon in the systray and firefox opened (it can be any window).
 
 
![image](https://user-images.githubusercontent.com/42818929/134203258-2a205f2a-0701-4aed-b0e3-0c24d7dde105.png)
This is how the bar behaves once I close all the windows in the workspace. Notice the "CPU" now being "PU".

The issue is not related to the bar script(s), which I reverted back to the default ones provided in the .dwm/bar folder during troubleshooting, as I thought I messed up by changing stuff in the script to my liking.

**Comment by siduck76** [comment]
Idk if this will even work but can you try the gruvchad.sh bar script?  ( dont forget to include it in your autostart ) 

https://github.com/siduck76/chadwm/blob/main/.dwm/bars/gruvchad.sh

**Comment by baizeyv** [comment]
Oh! I think I can fix it!
Steps:
1. use a editor to edit 'dwm.c'
2. find the function named 'drawbar(Monitor *m)'
3. find the following content
if (m->sel) {
	drw_setscheme(...
if(m->sel->isfloating)
	drw_rect(...
}else {
	drw_setscheme(drw,...
	drw_rect(drw, x, y, w - m->gappov * 2, bh_n, 1, 1);
}
4. Modify it to the following
if (m->sel) {
	drw_setscheme(...
if(m->sel->isfloating)
	drw_rect(...
}else {
	drw_setscheme(drw,...
	drw_rect(drw, x, y, w - getsystraywidth() - m->gappov * 2, bh_n, 1, 1);
}

------
And...
In this function,
'if(showsystray && m==systraytomon(m))'
THIS POSITION!!!
Whether Should Has 'stw = getsystraywidth()'

I don't know.
But, I think this position has played a role that I don't know
So I add '-getsystraywidth()'to the drw_rect...

In my opinion, this reply will help you.

**Comment by siduck76** [comment]
@baizeyv did you try that fix yourself ? does it work for you ? if yes then send a PR!! I'll test it

**Comment by baizeyv** [comment]
@siduck76 
Origin Version:
has clients:
![2021-09-25_21-52](https://user-images.githubusercontent.com/76252320/134774996-dc14135a-3944-41c6-827e-d547ee463c66.png)
no client:
![2021-09-25_21-52_1](https://user-images.githubusercontent.com/76252320/134775001-8e35175d-1119-4f10-9901-50cbd0892be0.png)

Modify Version:
has clients:
![2021-09-25_21-52_2](https://user-images.githubusercontent.com/76252320/134775010-94dad7c5-3269-47a9-a4a4-df5926de4424.png)
no client:

![2021-09-25_21-53](https://user-images.githubusercontent.com/76252320/134775017-da64c2f7-d833-4f1d-b7bc-77c20768ac38.png)
