### ISSUE TITLE
patches

### ISSUE THREAD

**Issue by wael444** [siduck76/chadwm#39]
this is more of an request than it is an issue,

for example with status2d modified to fit statuspadding + systray, you could turn it into a patch for others to use
the reason i had actually opened this issue is because i ~~shamingly~~ copied chadwm's `updatesystrayicongeom` but it gave me 
![image](https://user-images.githubusercontent.com/47404953/135727863-6892b645-6dfa-4c18-ac3b-0defe178cfe9.png)
which prompted me that i did something wrong.

will it ever be possible to turn most features implented in chadwm into it's own individual patch?

**Comment by siduck76** [comment]
my friend a lot while patching the systray+status2d , maybe you could check the commit history +_+

**Comment by wael444** [comment]
> my friend a lot while patching the systray+status2d , maybe you could check the commit history +_+

going through all of the commits or blames will take plenty of time, but due to the undocumented code it will be harder.

thanks for the suggestion but I have tried (probably not hard enough? who knows.)

**Comment by baizeyv** [comment]
@wael444 whether would you want to reset the position of systray?  The systray be put to the center of its panel? If yes, maybe you can view this [site](https://github.com/baizeyv/SnazzyDWM/commit/846c1d8b6fe436da9b1a2235a12ebf9316adf492) which is my repository of 'dynamic window manager'. Although I like mine, I recommend that the best choice is to use the 'chadwm'.
Make modifications while standing on the shoulders of giants.
Also, you can patch some patches you like but not on the official site to yours. For example, while you patch 'statuspadding' patch you will think that how to change the position, then you will find the corresponding function and make modifications. This process will make you study more and more knowledge.:)

**Comment by wael444** [comment]
> @wael444 whether would you want to reset the position of systray?  The systray be put to the center of its panel? If yes, maybe you can view this [site](https://github.com/baizeyv/SnazzyDWM/commit/846c1d8b6fe436da9b1a2235a12ebf9316adf492) which is my repository of 'dynamic window manager'. Although I like mine, I recommend that the best choice is to use the 'chadwm'.

my way to doing my configurations is terrible but what I would do is to get the complete defaults then add my stuff on it 


> Also, you can patch some patches you like but not on the official site to yours.

many good patches on dwm are not on the patches site on suckless.org
 
> For example, while you patch 'statuspadding' patch you will think that how to change the position, then you will find the corresponding function and make modifications. This process will make you study more and more knowledge.:)

thank you for helping.

though I got my systray icon size patch thanks to @baizeyv , I will still try to figure out how I can do the rest of the things that I would like it to do taking all of above into consideration.

**Comment by baizeyv** [comment]
@wael444 Did you mean this [patch](https://github.com/baizeyv/dwm-awesomeextrabar-6.2/blob/main/dwm-systray-statuspadding-6.2.diff)?
I merge the clean version patch just now.
(statuspadding+systray)

**Comment by wael444** [comment]
@baizeyv I'm not sure, I just need systray+statuspadding+status2d+(perhaps barpadding since I want to experiment) though thats already implemented in chadwm so I just simply copy.

**Comment by baizeyv** [comment]
@wael444 [this](https://github.com/baizeyv/dwm-awesomeextrabar-6.2/blob/main/dwm-systray-statuspadding-status2d-6.2.diff)
if you want to add barpadding, you can look at my repo.
function: drawstatusbar();
you could search content in this function.
Content: 'sp' or 'vp'
they are the marks of barpadding
