### ISSUE TITLE
Permission to package.

### ISSUE THREAD

**Issue by Shinyzenith** [siduck76/chadwm#40]
Hey! @siduck76 I have packaged your dwm build with some modifications and converted your `bar.sh` into a binary ( dwmblocks ) which I hope to integrate into my GNU/Linux Distribution ( https://github.com/xelphlinux ).

The least I can do to acknowledge that the build was not my own hard-work, is to ask you for a permit to package although the repository is under the MIT license.

**Comment by siduck76** [comment]
@Shinyzenith I wouldnt mind unless you credit me :))

**Comment by Shinyzenith** [comment]
![image](https://user-images.githubusercontent.com/60808802/135876856-84a963ee-5494-40ca-8a56-1635840180a5.png)
Absolutely, they're in the PKGBUILD and I forked from your repo so it's evident.
Should I put comments with the same in the source code?

**Comment by Shinyzenith** [comment]
just noticed that my autocorrect wrote sideduck XD fixing that.

**Comment by Shinyzenith** [comment]
![image](https://user-images.githubusercontent.com/60808802/135878477-4077f766-3c95-4b70-b4e5-cba5e6604398.png)
Fixed!
