### ISSUE TITLE
Icon font size?

### ISSUE THREAD

**Issue by mrgreen3** [siduck76/chadwm#42]
Have got chadwm set up without any issues, simply wanted to know how to increase size of icon fonts in bar? 

Mr Green

**Comment by siduck76** [comment]
config.def.h font size

**Comment by siduck76** [comment]
> Changed both and Clock one looked huge.... but Tag icons are tiny! Update and Memory one are small too.... Not like in your screenshots. Which are amazing!!!!

what font did you change to

**Comment by mrgreen3** [comment]
What was in config.def.h ..... Adding a normal tag and it matches rest of text on bar. Think it is the font icons that are the issue

`static const char *fonts[]          = { "JetBrainsMono Nerd Font:style:medium:size=10",
                                          "Material Design Icons-Regular:size=10",
`
Think I have found issue, put font directory from repo in ~/.local/share/fonts doh!!!

**Comment by mrgreen3** [comment]
Changed size of Material Design Icons in config.h all that does is makes the system info icons larger [wifi and clock]. Not the ones in tags [the ones I would like larger].
