### ISSUE TITLE
Great project - nice look and feel 

### ISSUE THREAD

**Issue by erikdubois** [siduck76/chadwm#44]
I have made a promotion video for your project here : 

https://youtu.be/YSasXSPkyok

If I may make a suggestion. 

1. Create a .desktop file for users to put into /usr/share/xsessions
2. Rename your desktop to chadwm or something else but not dwm as it will conflict with the actual dwm - compare with alci-dwm to see how it can be done
3. put the autostart somewhere else so we can execute it without needing to change the /home/**username**/.dwm/autostart - /usr/local/bin?

Great job have fun developing it further

![image](https://user-images.githubusercontent.com/10594806/137932143-1ce6f006-86f2-42b7-8147-8a87c25aabbf.png)

**Comment by siduck76** [comment]
chadwm's still WIP so I have to clean lots of stuffs and organize it by a bit, will add more featureful eww widgets in the future too.
