### ISSUE TITLE
[Feature] Add tag preview  (WIP)

### ISSUE THREAD

**Issue by siduck76** [siduck76/chadwm#6]
show a floating picture like thingy for tags when their icons on dwmbar is hovered, something like this 

https://cdn.discordapp.com/attachments/635625917623828520/829478089469329438/gif_2021-04-07032620.gif
(awesomewm)

**Comment by siduck76** [comment]
so far I was able to preview an image with rofi and align it properly.


https://user-images.githubusercontent.com/59060246/127742653-501087b4-9ff9-4c5c-b3a9-c1c29e87138d.mp4

**Comment by siduck76** [comment]
`
#!/bin/sh

 preview_dir="$HOME/.dwm/tag_previews/"

 current_tag=$(wmctrl -d | grep '*' | cut -d ' ' -f1)

 file="${preview_dir}${current_tag}.png"
 maim "${file}"
  
`

**Comment by siduck76** [comment]
The above script should be before the user switches to another workspace. (this is for saving the screenshots ) 
 
 maim will update the screenshots itself too.

**Comment by siduck76** [comment]
### Basic Concept for this!

- Run the above script before switching tags
- Hovering on a tag icon execute this : , suppose there are 5 workspaces ( 0 to 4 according to wmctrl ) and If 
I hover  on tag 1 then  this will be executed : 

screenshot=".dwm/tag_previews/1.png"

sed -i "s:/home/sid/.*\.png:/home/sid/$screenshot:" ~/.config/rofi/tag.rasi

rofi -show -drun -theme tag

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/127776548-f5c22a36-8801-46a2-bbea-b687e8a86eef.mp4

works kinda ( but switching tags adds 100ms ~ delay ) :(

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/127789831-81e0a856-8032-4241-b180-29c3a5aacba5.mp4

after using jpeg for image format , it feels faster than before!

**Comment by siduck76** [comment]
using feh instead of rofi is much faster!


https://user-images.githubusercontent.com/59060246/127867063-ba7572fd-bdb6-413e-98c1-ce348395f5b0.mp4

**Comment by siduck76** [comment]
1. So we dont need some hooks stuff , since the tag preview is accurate (but not for current tag). the rest of the tags already have accurate previews ,since we're taking screenshot before switching the tag.

look 

https://user-images.githubusercontent.com/59060246/127945072-45f1bd3b-9b34-4d86-8a49-4bb4d9fb29e7.mp4

**Comment by siduck76** [comment]
Issue 2 :

If there's an inactive tag , do not show its tag preview.

behaviour : 


https://user-images.githubusercontent.com/59060246/127945471-32eb62d6-6935-4cde-8620-ebea330f759c.mp4

Solution : 

just delete its image from the ~/.dwm/tag_previews dir soo in our case 3 was the inactive tag , so remove 3.jpeg :) 

if we hover an empty tag

**Comment by siduck76** [comment]
finally my friend made a patch for this! so no external scripts xD

https://github.com/siduck76/chadwm/commit/0372264f1de4aa3487a0c1643051dd5746e0e581

**Comment by siduck76** [comment]
stuff needs to be fixed :  tag preview doesnt update the current workspace screenshot 
https://user-images.githubusercontent.com/59060246/128020338-268f591e-5004-44a1-811b-425acd8af8b1.mp4


solution : whenever we hover current tag icon , take screenshot + do tag preview

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/128049070-338f3cec-ac21-4a4a-ae42-ca23ef035839.mp4

**Comment by siduck76** [comment]
https://github.com/siduck76/chadwm/commit/75168cc5d5efe9d34b00318259244ff60ccafd20

**Comment by siduck76** [comment]
dwm ram usage keeps increasing if I switch to a different tag 


https://user-images.githubusercontent.com/59060246/128053620-632f043b-b037-4a3b-a5c1-f2cb9241d620.mp4

**Comment by siduck76** [comment]
> dwm ram usage keeps increasing if I switch to a different tag
> 
>  simplescreenrecorder-2021-08-03_21.49.19.mp4

temp fix https://pastebin.com/raw/rThCDTZ6

**Comment by siduck76** [comment]
> dwm ram usage keeps increasing if I switch to a different tag
> 
>  simplescreenrecorder-2021-08-03_21.49.19.mp4

fixed here https://github.com/siduck76/chadwm/commit/a10d00f9e0329e787b490e54182f15394e41b583

**Comment by siduck76** [comment]
dwm will know take around 11mb to 32~ mb , since its storing the images in ram rather than disk . I'll test it the other way around  ( saving images on disk).

**Comment by siduck76** [comment]
FINALLY DONE https://github.com/siduck76/chadwm/commit/f397a51a8e9b093994bc663be4d98cc7150bdb81

thanks a lot to /u/eProTaLT83 for helping with this feature!!

**Comment by explosion-mental** [comment]
Hi, made a [patch](https://github.com/explosion-mental/Dwm/blob/main/Patches/dwm-tag-preview-6.2.diff) for this, which of course I can maintain. 

Let me suggest to put it on the patches section since I know some are too comfy on their builds to switch.

**Comment by siduck76** [comment]
> Hi, made a [patch](https://github.com/explosion-mental/Dwm/blob/main/Patches/dwm-tag-preview-6.2.diff) for this, which of course I can maintain.
> 
> Let me suggest to put it on the patches section since I know some are too comfy on their builds to switch.

Thanks for this! if you don't mind then you could add the tabbed with colored buttons patch too.

**Comment by explosion-mental** [comment]
> Thanks for this! if you don't mind then you could add the tabbed with colored buttons patch too.

You mean [this](https://github.com/siduck76/chadwm/issues/17) ?

**Comment by siduck76** [comment]
> > Thanks for this! if you don't mind then you could add the tabbed with colored buttons patch too.
> 
> You mean [this](https://github.com/siduck76/chadwm/issues/17) ?

yes

**Comment by explosion-mental** [comment]
Sorry for the late response but the [patch](https://dwm.suckless.org/patches/tag-previews/) finally got pushed.
Also by
> Let me suggest to put it on the patches section since I know some are too comfy on their builds to switch.
I meant to the readme of your repo lol. Anyway it's now pushed on the link above.

As for
> if you don't mind then you could add the tabbed with colored buttons patch too.
I could but I wouln't be able to keep it up to date.

**Comment by siduck76** [comment]
@explosion-mental The author of the patch is  /u/eProTaLT83  on reddit . I came up with this idea and he made a patch for it!
