### ISSUE TITLE
tag preview crashes dwm

### ISSUE THREAD

**Issue by CSpencerND** [siduck76/chadwm#94]
Everything works fine on single monitor, but once I enable a second monitor, then switch tags on the secondary monitor, the status bar disappears and all my keybindings stop working. I have to`sudo pkill X` to get out. This happens even on a fresh clone of the repo without any changes done to the config besides enabling tag preview.

**Comment by siduck** [comment]
> [bakkeby/dwm-flexipatch@9728c3a](https://github.com/bakkeby/dwm-flexipatch/commit/9728c3aad6806c5d0bb2626012581b314c9ce80e)

does it fix your issue?

**Comment by CSpencerND** [comment]
Yes

**Comment by siduck** [comment]
add a PR for it if you can :)
